#!/bin/bash
#####################################################
## backup-script by Frickelpit using rsync 	   ##
## created for learning some bash skills	   ##
#####################################################

## dirs ##
bdir="/mnt/backup/Apophis"
adir="/mnt/backup"
src="$HOME/"

## files ##
file="$HOME/.rsync-backupfile"
log="$HOME/.backup.log"

## vars ##
dte="$(date '+%F')"
pkgh="$(grep -c ">f" "$log")"

if ! "$bdir" &>/dev/null ;then
  notify-send "Abbruch" "Zielverzeichnis nicht gefunden"
  exit;
elif pgrep [f]irefox &>/dev/null ;then
  notify-send "Abbruch" "Bitte zuerst Firefox schließen"
  exit;
elif ! "$file" &>/dev/null ;then
  notify-send "Abbruch" "Bitte $file anlegen"
  exit;
fi

notify-send "Backup von $src wird gestartet…"
> "$log"
if [[ -f $bdir/paclist.txt ]];then
  mv "$bdir"/paclist.txt "$bdir"/"$dte".paclist.txt
fi
pacman -Qeq > "$bdir"/paclist.txt
if ! rsync -avz --progress --exclude-from="$file" --log-file="$log" "$src" "$bdir" ;then
  notify-send "Warnung!" "Daten konnten nicht gesichert werden!"
else
  notify-send "Sicherung abgeschlossen" "$pkgh Datei(en) gesichert"
fi

notify-send "Archiv wird angelegt…"
if ! tar cjf "$adir"/"$dte".backup.tar.bz2 "$bdir" ;then
  notify-send "Archiv konnte nicht angelegt werden."
else
  notify-send "Archiv erfolgreich angelegt."
fi
