#!/bin/bash
#####################################################
## backup-script by Frickelpit using rsync 	   ##
## created for learning some bash skills	   ##
#####################################################

## dirs ##
ssh_host="pit@srv01"
homebdir="backup/x220"
home="$HOME/"

## files ##
homefile="$HOME/.rsync-backupfile"
log="$HOME/.backup.log"

## vars ##
dte="$(date '+%F')"

if ! nmap 192.168.178.200 -p 22  |  grep "open" -q; then
  notify-send "connection to ${ssh_host} refused"
  exit 1;
elif [[ ! -f "$homefile" ]]; then
  notify-send "Aborted" "file missing"
  exit 1;
elif pgrep [f]irefox &>/dev/null; then
  notify-send "Aborted" "running firefox detected, please close your browser first"
fi

notify-send "Starting backup" "Sending files to ${ssh_host}"
> "$log"
if [[ -f "$ssh_host:$homebdir"/.paclist.txt ]]; then
   mv "$ssh_host:$homebdir"/paclist.txt "$ssh_host:$homebdir/$dte".paclist.txt
fi
pacman -Qeq > "$home"/.paclist.txt
rsync -ahve ssh --numeric-ids --progress --exclude-from="$homefile" --log-file="$log" "$home" "$ssh_host:$homebdir"

if [[ $? -ne 0 ]];then
  notify-send "Error!" "Backup not completed, see $log for more info"
else
  notify-send "Backup finished" "Files saved to ${ssh_host}"
fi
