#!/bin/bash
# DWM status script
 
## Colors ######################
## 01 = normal	02 = selected ##
## 03 = red	04 = green    ##
## 05 = yellow	06 = blue     ##
## 08 = magenta	09 = grey     ##
################################

dte(){
dte="$(date '+%H:%M')"
printf "%b" "$dte"
}

bat(){
battdir='/sys/class/power_supply/BAT0'
perc="$(</sys/class/power_supply/BAT0/capacity)"
online="$(</sys/class/power_supply/AC/online)"
if [[ ! -d $battdir ]]; then
   printf "%b" "AC only"
else
   if [[ $online -eq 0 && $perc -le 10 ]]; then
      printf "%b" "BAT $perc" && notify-send "Akkuladung bei "$perc" Prozent!"
   elif [[ $online -eq 0 && $perc -le 100 ]]; then
      printf "%b" "BAT $perc"
   else
      printf "%b" "AC $perc"
   fi
fi
}

vol(){
mute=$(amixer get Master | grep "Mono:" | awk '{print $6}')
vol=$(amixer get Master | grep -m 1 -o '[0-9][0-9]*%'| sed 's/\%//g')
if [[ "$mute" == "[on]" ]]; then
   printf "%b" "VOL $vol"
else
   printf "%b" "VOL $vol"
fi
}

net(){
lan="$(</sys/class/net/enp0s25/operstate)"
wlan="$(</sys/class/net/wlp3s0/operstate)"
case up in
	$wlan)
	printf "%b" "NET ON"
	;;
	$lan)
	printf "%b" "LAN ON"
	;;
	*)
	printf "%b" "NET OFF"
	;;
esac
}

cpu(){
temp=$(tlp-stat -t | awk '/CPU/ {printf $4}')
if (( temp > 70 )); then
   printf "%b" "CPU $temp°C"
else
   printf "%b" "CPU $temp°C"
fi
}

pac(){
pac="$(pacman -Qqu --dbpath /tmp/checkup-db-pit/ | wc -l)"
if (( pac > 0 )); then
   printf "%b" "PAC $pac"
else
   printf "%b" "PAC 0"
fi
}

aur(){
ups="$(wc -l </tmp/aurupdates*)"
if (( ups > 0 )); then
   printf "%b" "AUR $ups"
else
   printf "%b" "AUR 0"
fi
}

# Pipe to status bar
while true; do
   xsetroot -name "$(pac) • $(aur) • $(cpu) • $(vol) • $(net) • $(bat) • $(dte)"
   sleep 30
done
