#!/bin/sh

# Display the number of installed packages,
# version of the kernel and gcc used.

ALL=$(pacman -Q | wc -l)
EXPL=$(pacman -Qe | wc -l)
LOCAL=$(pacman -Qm | wc -l)
ORPH=$(pacman -Qqdt | wc -l)
KERNEL=$(uname -r)
GCC=$(gcc --version | head -n1 | cut -c 11-38)
SETUP=$(grep -i 'installed filesystem' /var/log/pacman.log | cut -c 2-17)

echo "$ALL installed packages altogether";
echo "$EXPL explicitly installed packages";
echo "$LOCAL localy installed packages.";
echo "$ORPH packages installed as dependencies which are no longer needed."
echo "Your system was originally set up $SETUP"
echo "You are using kernel $KERNEL and gcc version $GCC."
